app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/',['as'=>'home','uses'=>'SeoController@show']); 
Route::get('/categories',['as'=>'categories','uses'=>'SeoController@showCategories']);
Route::get('/categories/{category}','SeoController@categoryPosts');
Route::post('/login','SeoController@doLogin');
Route::get('/logout',['as'=>'logout','uses'=>'SeoController@doLogout']);
  
/*========== Admin area controllers *============= */
Route::get('/seodashboard',['middleware'=>'isAdmin','as'=>'dashboard','uses'=>'PostController@showDashboard']);
Route::resource('/seodashboard/posts','PostController');
Route::resource('/seodashboard/categories','CategoryController');
Route::get('/seodashboard/comments',['as'=>'comment','uses'=>'CommentController@show']);

Route::post('seo/ajax','SeoController@ajax');

resources/views/admin/allposts.blade.php
@extends('admin.main')
@section('title')
All posts
@stop
@section('content')
<table class="table table-hover">
	<thead>
		<th>Title</th>
		<th>author</th>
		<th>views</th>
		<th>status</th>
		<th>Seo title</th>
		<th>Seo description</th>
		<th>Seo keywords</th>
		<th>Edit</th>
		<th>Delete</th>
	</thead>
	<tbody>
	@foreach($posts as $post)
	<tr>
		<?php $title=urlencode($post->title); ?>
		<td><a href="{{action('PostController@show',[$title])}}">{{$post->title}}</a></td>
		<td>Lorem ipsum</td>
		<td>0</td>
		<td>@if($post->published)
			{{"published"}}
			@else
			{{"Draft"}}

			@endif

		</td>
		<td>{{$post->title}}</td>
		<td>{{$post->excrypt}}</td>
		<td>
			<ul>
			@foreach($post->tags as $tag)
			
				<li>{{$tag->tag}}</li>
			
			@endforeach
			</ul>
		</td>
		<td><a href="{{route('seodashboard.posts.edit', $post->id) }}" class="btn btn-success">Edit</a></td>
		<td>
				{!! Form::open(['method'=>'DELETE','route'=>['seodashboard.posts.destroy',$post->id]]) !!}
				{!! Form::submit('Delete',['class'=>'btn btn-danger'])!!}
				{!! Form::close() !!}
			</td>
	</tr>

	@endforeach
		
	</tbody>
</table>

@stop

resources/views/admin/cat.blade.php
@extends('admin.main')
@section('title')
categories
@stop
@section('content')
{!!Form::open(array('url'=>'seodashboard/categories')) !!}
	<div class="form-group">
		<div class="row">
			<div class="col-sm-1">
			{!!Form::label('category') !!}
			</div>
			<div class="col-sm-4">
			{!!Form::text('cat',null,['class'=>'form-control']) !!}
			</div>

		</div>
</div>
	<div class="form-group">
		<div class="row">
			<div class="col-sm-1">
			{!!Form::label('Description') !!}
			</div>

			<div class="col-sm-5">
				{!!Form::textarea('description',null,['class'=>'form-control']) !!}
			</div>
		</div>
</div>

<div class="form-group">
	<div class="row">
	<div class="col-sm-2">
	{!!Form::label('parent') !!}
	</div>
	<div class="col-sm-3">
	<select name="category_parent" class="form-control">
		<option value="0">None</option>
		@foreach($categories as $category)
			<option value="{{$category->id}}">{{$category->category}}</option>

		@endforeach
	</select>
	</div>
	</div>
</div>
			<div class="col-sm-offset-2 col-sm-3">
			{!!Form::submit('Add',array('class'=>'btn btn-success form-control'))!!}
			</div>


{!! Form::close()!!}

<table class="table table-hover">
	<thead>
		<th>category</th>
		<th>Edit</th>
		<th>Delete</th>
	</thead>
	<tbody>
	@foreach($categories as $category)
	<tr>
		<td>{{$category->category}}</td>
		<td><a href="{{route('seodashboard.categories.edit',$category->id) }}" class="btn btn-success">Edit</a></td>
		<td>
				{!! Form::open(['method'=>'DELETE','route'=>['seodashboard.categories.destroy',$category->id]]) !!}
				{!! Form::submit('Delete',['class'=>'btn btn-danger'])!!}
				{!! Form::close() !!}
			</td>
	</tr>

	@endforeach

	</tbody>
@stop

resources/views/admin/comment.blade.php
@extends('admin.main')
@section('title')
Comment
@stop
@section('content')
<p class="lead">
 	Area of comments
</p>
@stop

resources/views/admin/create.blade.php
@extends('admin.main')
@section('title')
New Post
@stop
@section('content')
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

{!!Form::open(array('url'=>'/seodashboard/posts', 'files' => true)) !!}
 <div class="form-group">
 <div class="row">
    <label for="exampleInputEmail1" class="col-sm-1">Title</label>
    <div class="col-sm-4">
    {!!Form::text('title',null,['class'=>'form-control','placeholder'=>'add your post title here']) !!}
    </div>
    <label class="col-sm-1 col-sm-offset-2">status</label>
    <div class="col-sm-3">

    {!!Form::select('status',array('1'=>'published','0'=>'draft'),null,['class'=>'form-control'])!!}
    </div>
    </div>
  </div>
  <div class="form-group">
      <div class="row">
        <div class="col-sm-2">
          {!!Form::label('Meta description')!!}
        </div>
        <div class="col-sm-4">
          {!!Form::textarea('excrypt',null,['id'=>'excrypt','class'=>'form-control','required'=>'required','placeholder'=>'max character is 155'])!!}
        </div>
     </div>
  </div>

  <div class="row">
    <div class="col-sm-2">
    Number of characters
    </div>
    <div class="col-sm-1">
      <div id="counter"></div>
    </div>
  </div>
  
  <div class="form-group">
      {!!Form::label('post body')!!}

    {!!Form::textarea('content',null,['id'=>'editor','class'=>'form-control','required'=>'required'])!!}

  </div>
  <div class="form-group">
  <div class="row">
      <div class="col-sm-1">
       {!!Form::label('Keywords')!!}
</div>

      <div class="col-sm-4">
       {!!Form::select('tags[]',$tags,null,['id'=>'tags','class'=>'form-control','multiple'])!!}
      </div>
    <div class="col-sm-1">
       {!!Form::label('Category')!!}
</div><div class="col-sm-4">
            {!!Form::select('categories[]',$category,null,['id'=>'category','class'=>'form-control','multiple'])!!}
      </div>
  </div>
</div>
 <div class="form-group">
    <label for="exampleInputFile">Post Image</label>
    <input type="file" id="exampleInputFile" name="image">
 </div>

  {!!Form::submit('Create',array('class'=>'btn btn-success form-control'))!!}

{!! Form::close()!!}
 
{!!Form::close() !!}


@stop

resources/views/admin/dashboard.blade.php
@extends('admin.main')
@section('title')
Seo Dashboard
@stop
@section('content')
<h1 class="page-header">Dashboard</h1>
<p class="lead">
	this section will contain a statiscs of posts and comments and users who wrote last posts
	<ul>
		<li> statistics</li>
		<li> notifications</li>
	</ul>
</p>
  @stop

resources/views/admin/edit.blade.php
@extends('admin.main')
@section('title')
edit
@stop
@section('content')
{!!Form::model($post,['method'=>'PATCH','action'=>['PostController@update',$post->id], 'files' => true])!!}

<div class="form-group">
 <div class="row">
    <label for="exampleInputEmail1" class="col-sm-1">Title</label>
    <div class="col-sm-4">
    {!!Form::text('title',null,['class'=>'form-control']) !!}
    </div>
    <label class="col-sm-1 col-sm-offset-2">status</label>
    <div class="col-sm-3">

    {!!Form::select('status',array('1'=>'published','0'=>'draft'),$post->published,['class'=>'form-control'])!!}
    </div>
    </div>
  </div>
  <div class="form-group">
    {!!Form::label('Meta description')!!}

    {!!Form::textarea('excrypt',null,['id'=>'excrypt','class'=>'form-control','required'=>'required'])!!}

  </div>
  <div id="counter"></div>
  <div class="form-group">
      {!!Form::label('post body')!!}

    {!!Form::textarea('content',null,['id'=>'editor','class'=>'form-control','required'=>'required'])!!}

  </div>
  <div class="form-group">
  <div class="row">
      <div class="col-sm-1">
       {!!Form::label('Keywords')!!}
</div>

      <div class="col-sm-4">
       {!!Form::select('tags[]',$tags,$post->getTagListAttribute(),['id'=>'tags','class'=>'form-control','multiple'])!!}
      </div>
    <div class="col-sm-1">
       {!!Form::label('Category')!!}
</div><div class="col-sm-4">
            {!!Form::select('categories[]',$category,$post->getCategoryListAttribute(),['id'=>'category','class'=>'form-control','multiple'])!!}
      </div>
  </div>
</div>
 <div class="form-group">
    <label for="exampleInputFile">Post Image</label>
    <input type="file" id="exampleInputFile" name="image">
 </div>

  {!!Form::submit('Update',array('class'=>'btn btn-success form-control'))!!}

{!! Form::close()!!}

 
{!!Form::close() !!}


@stop

resources/views/admin/editcat.blade.php
@extends('admin.main')
@section('title')
edit categories
@stop
@section('content')
{!! Form::model($category,['method'=>'PATCH','action'=>['CategoryController@update',$category->id]])!!}
<div class="form-group">
		<div class="row">
			<div class="col-sm-1">
			{!!Form::label('category') !!}
			</div>
			<div class="col-sm-4"> 
			{!!Form::text('cat',$category->category,['class'=>'form-control']) !!}
			</div>

		</div>
</div>
	<div class="form-group">
		<div class="row">
			<div class="col-sm-1">
			{!!Form::label('Description') !!}
			</div>

			<div class="col-sm-5">
				{!!Form::textarea('description',$category->description,['class'=>'form-control']) !!}
			</div>
		</div>
</div>

<div class="form-group">
	<div class="row">
		<div class="col-sm-2">
		{!!Form::label('parent') !!}
		</div>
		<div class="col-sm-3">
		{!!Form::select('category_parent',$category_list,$category->parent_id,['class'=>'form-control']) !!}
		</div>
	</div>
</div>
			<div class="col-sm-offset-2 col-sm-3"> 
			{!!Form::submit('update',array('class'=>'btn btn-success form-control'))!!}
			</div>


{!! Form::close()!!}
@stop

resources/views/admin/main.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="title" content="@yield('metatitle')">
    <meta name="description" content="@yield('metadesc')">
    <meta name="keywords" content="@yield('keywords')">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>@yield('title')</title>

    <!-- Bootstrap -->
    <link href="{!!asset('css/bootstrap.min.css')!!}" rel="stylesheet">
    <link href="{!!asset('css/adminstyle.css')!!}" rel="stylesheet">
    <link href="{!!asset('css/font-awesome/css/font-awesome.min.css')!!}" rel="stylesheet">

      <link href="{!! asset('select2/css/select2.min.css') !!}" rel="stylesheet" />
      <script src="{!! asset('js/jquery-1.11.3.min.js')!!}"></script>

      <script src="{!! asset('select2/js/select2.min.js') !!}"></script>
       </head>
  <body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{!!route('dashboard') !!}"><i class="fa fa-tachometer fa-2x fa-fw"></i>
Seo Dashboard</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">

           <ul class="nav navbar-nav navbar-right">
           <li><a href="{{route('home')}}"><i class="fa fa-globe fa-lg fa-fw"></i>
Visit site</a></li>
    <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <i class="fa fa-bell fa-lg fa-fw"></i> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#"> Not 1</a></li>
            <li><a href="#"> Not 2</a></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <i class="fa fa-user fa-lg fa-fw"></i>{{Auth::user()->name}} <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#"> <i class="fa fa-pencil fa-lg fa-fw"></i>edit</a></li>
            <li><a href="{{route('logout')}}"> <i class="fa fa-sign-out fa-lg fa-fw"></i>logout</a></li>
          </ul>
        </li>
      </ul>
        </div>
      </div>
    </nav>
  <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li><a href="{!!route('dashboard') !!}"><i class="fa fa-tachometer"></i>
Dashboard <span class="sr-only">(current)</span></a></li>
            <li><a href="javascript:;" data-toggle="collapse" data-target="#demo"><i class="fa fa-sort-desc fa-2x"></i> &nbsp;Posts</a></li>
            <ul id="demo" class="collapse" style="list-style-type: none;">
            <li><a href="{{route('seodashboard.posts.index')}}"><i class="fa fa-folder-open fa-lg fa-lw"></i>
All posts</a></li>
            <li><a href="{!!route('seodashboard.posts.create')!!}"> <i class="fa fa-plus fa-lg fa-lw"></i>
New Post</a></li>
            </ul>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="{!! route('seodashboard.categories.index')!!}"><i class="fa fa-bars fa-lg fa-fw"></i>Categories</a></li>
            <li><a href="{!!route('comment') !!}"> <i class="fa fa-comment-o fa-lg fa-fw"></i>
Comments</a></li>
            <li><a href="#"> <i class="fa fa-users fa-lg fa-fw"></i>
Users</a></li>
            <li><a href="#"> <i class="fa fa-user fa-lg fa-fw"></i>
Profile</a></li>
          </ul>

        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        @yield('content')



        </div>
      </div>
    </div>
  <script type="text/javascript">

      $("#tags").select2({
          tags: true,
          tokenSeparators: [',', ' ']

      });
      $("#category").select2({
          tags: true,
          tokenSeparators: [',', ' ']

      });
  </script>
<script src="{!!asset('js/ckeditor/ckeditor.js') !!}"></script>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->


    <script src="{!! asset('js/jquery-1.11.3.min.js')!!}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{!! asset('js/bootstrap.min.js')!!}"></script>
  <script src="{!! asset('js/plugin.js')!!}"></script>
  </body>
</html>

resources/views/admin/media.blade.php
@extends('admin.main')
@section('title')Media@stop
@section('content')



@stop

resources/views/admin/post.blade.php
@extends('admin.main')
@section('title')
{{$post->title}}@stop
@section('metatitle')
{{$post->title}}@stop
@section('metadesc')
{{$post->excrypt}}@stop
@section('keywords')
{{$keyword}}@stop
@section('content')
<h1><img class="img-thumbnail" src="{{asset('images/'.$post->image)}}" height="140px" width="140px" />
{{$post->title}}</h1>
<hr>
{!!  $post->content !!}
@stop